# Benjamin Steenkamer and Abraham McIlvaine
# CPEG 324-010
# Lab 2: VHDL Componetns
# 4/X/17

GHDL = ./../ghdl/bin/ghdl
COMP = -a --ieee=standard
EXE = -e --ieee=standard
RUN = -r

test-4bit-as:
	  $(GHDL) $(COMP) ../4_bit_add_sub.vhdl
	#   $(GHDL) $(COMP) ../4_bit_add_sub_tb.vhdl
	#   $(GHDL) $(EXE) ../4_bit_add_sub_tb
	# $(GHDL) $(RUN)
